/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as TerminalsIndexRouteImport } from './routes/terminals/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as StakeholdersIndexRouteImport } from './routes/stakeholders/index'
import { Route as SelfServiceIndexRouteImport } from './routes/self-service/index'
import { Route as SecurityIndexRouteImport } from './routes/security/index'
import { Route as RosterIndexRouteImport } from './routes/roster/index'
import { Route as RgmIndexRouteImport } from './routes/rgm/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as PositionsIndexRouteImport } from './routes/positions/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as InspectionsIndexRouteImport } from './routes/inspections/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as GeofenceIndexRouteImport } from './routes/geofence/index'
import { Route as DocumentsIndexRouteImport } from './routes/documents/index'
import { Route as DepartmentsIndexRouteImport } from './routes/departments/index'
import { Route as ContractorsIndexRouteImport } from './routes/contractors/index'
import { Route as CertificationsIndexRouteImport } from './routes/certifications/index'
import { Route as AttendanceIndexRouteImport } from './routes/attendance/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StakeholdersVerificationRouteImport } from './routes/stakeholders/verification'
import { Route as StakeholdersPermitsRouteImport } from './routes/stakeholders/permits'
import { Route as StakeholdersStakeholderIdRouteImport } from './routes/stakeholders/$stakeholderId'
import { Route as StakeholderRegistrationSuccessRouteImport } from './routes/stakeholder/registration-success'
import { Route as StakeholderRegisterRouteImport } from './routes/stakeholder/register'
import { Route as StakeholderProfileRouteImport } from './routes/stakeholder/profile'
import { Route as StakeholderPermitsRouteImport } from './routes/stakeholder/permits'
import { Route as StakeholderLoginRouteImport } from './routes/stakeholder/login'
import { Route as StakeholderInvoicesRouteImport } from './routes/stakeholder/invoices'
import { Route as StakeholderFlightsRouteImport } from './routes/stakeholder/flights'
import { Route as StakeholderDashboardRouteImport } from './routes/stakeholder/dashboard'
import { Route as StakeholderActivitiesRouteImport } from './routes/stakeholder/activities'
import { Route as RosterMyShiftsRouteImport } from './routes/roster/my-shifts'
import { Route as RosterGenerateRouteImport } from './routes/roster/generate'
import { Route as PublicDutyBoardRouteImport } from './routes/public/duty-board'
import { Route as OrganizationsNewRouteImport } from './routes/organizations/new'
import { Route as OrganizationsOrgIdRouteImport } from './routes/organizations/$orgId'
import { Route as MessagesNewRouteImport } from './routes/messages/new'
import { Route as MessagesConversationIdRouteImport } from './routes/messages/$conversationId'
import { Route as GroupsGroupIdRouteImport } from './routes/groups/$groupId'
import { Route as DocumentsNewRouteImport } from './routes/documents/new'
import { Route as DocumentsDocIdRouteImport } from './routes/documents/$docId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTanchatRouteImport } from './routes/demo/tanchat'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoMcpTodosRouteImport } from './routes/demo/mcp-todos'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as RosterTemplatesIndexRouteImport } from './routes/roster/templates/index'
import { Route as ExampleGuitarsIndexRouteImport } from './routes/example.guitars/index'
import { Route as AdminStaffIndexRouteImport } from './routes/admin/staff/index'
import { Route as RosterTemplatesNewRouteImport } from './routes/roster/templates/new'
import { Route as OrganizationsOrgIdEditRouteImport } from './routes/organizations/$orgId.edit'
import { Route as ExampleGuitarsGuitarIdRouteImport } from './routes/example.guitars/$guitarId'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiTanchatRouteImport } from './routes/demo/api.tanchat'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoApiMcpTodosRouteImport } from './routes/demo/api.mcp-todos'
import { Route as AdminStakeholdersVerificationRouteImport } from './routes/admin/stakeholders/verification'
import { Route as AdminStaffNewRouteImport } from './routes/admin/staff/new'
import { Route as AdminRosterPlannerRouteImport } from './routes/admin/roster/planner'
import { Route as AdminAttendanceRegistryRouteImport } from './routes/admin/attendance/registry'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as AdminStaffIdEditRouteImport } from './routes/admin/staff/$id.edit'

const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalsIndexRoute = TerminalsIndexRouteImport.update({
  id: '/terminals/',
  path: '/terminals/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeholdersIndexRoute = StakeholdersIndexRouteImport.update({
  id: '/stakeholders/',
  path: '/stakeholders/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfServiceIndexRoute = SelfServiceIndexRouteImport.update({
  id: '/self-service/',
  path: '/self-service/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityIndexRoute = SecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterIndexRoute = RosterIndexRouteImport.update({
  id: '/roster/',
  path: '/roster/',
  getParentRoute: () => rootRouteImport,
} as any)
const RgmIndexRoute = RgmIndexRouteImport.update({
  id: '/rgm/',
  path: '/rgm/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsIndexRoute = PositionsIndexRouteImport.update({
  id: '/positions/',
  path: '/positions/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MessagesRoute,
} as any)
const InspectionsIndexRoute = InspectionsIndexRouteImport.update({
  id: '/inspections/',
  path: '/inspections/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeofenceIndexRoute = GeofenceIndexRouteImport.update({
  id: '/geofence/',
  path: '/geofence/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorsIndexRoute = ContractorsIndexRouteImport.update({
  id: '/contractors/',
  path: '/contractors/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsIndexRoute = CertificationsIndexRouteImport.update({
  id: '/certifications/',
  path: '/certifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceIndexRoute = AttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeholdersVerificationRoute =
  StakeholdersVerificationRouteImport.update({
    id: '/stakeholders/verification',
    path: '/stakeholders/verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const StakeholdersPermitsRoute = StakeholdersPermitsRouteImport.update({
  id: '/stakeholders/permits',
  path: '/stakeholders/permits',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeholdersStakeholderIdRoute =
  StakeholdersStakeholderIdRouteImport.update({
    id: '/stakeholders/$stakeholderId',
    path: '/stakeholders/$stakeholderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StakeholderRegistrationSuccessRoute =
  StakeholderRegistrationSuccessRouteImport.update({
    id: '/stakeholder/registration-success',
    path: '/stakeholder/registration-success',
    getParentRoute: () => rootRouteImport,
  } as any)
const StakeholderRegisterRoute = StakeholderRegisterRouteImport.update({
  id: '/stakeholder/register',
  path: '/stakeholder/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeholderProfileRoute = StakeholderProfileRouteImport.update({
  id: '/stakeholder/profile',
  path: '/stakeholder/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeholderPermitsRoute = StakeholderPermitsRouteImport.update({
  id: '/stakeholder/permits',
  path: '/stakeholder/permits',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeholderLoginRoute = StakeholderLoginRouteImport.update({
  id: '/stakeholder/login',
  path: '/stakeholder/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeholderInvoicesRoute = StakeholderInvoicesRouteImport.update({
  id: '/stakeholder/invoices',
  path: '/stakeholder/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeholderFlightsRoute = StakeholderFlightsRouteImport.update({
  id: '/stakeholder/flights',
  path: '/stakeholder/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeholderDashboardRoute = StakeholderDashboardRouteImport.update({
  id: '/stakeholder/dashboard',
  path: '/stakeholder/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeholderActivitiesRoute = StakeholderActivitiesRouteImport.update({
  id: '/stakeholder/activities',
  path: '/stakeholder/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterMyShiftsRoute = RosterMyShiftsRouteImport.update({
  id: '/roster/my-shifts',
  path: '/roster/my-shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterGenerateRoute = RosterGenerateRouteImport.update({
  id: '/roster/generate',
  path: '/roster/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDutyBoardRoute = PublicDutyBoardRouteImport.update({
  id: '/public/duty-board',
  path: '/public/duty-board',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsNewRoute = OrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrgIdRoute = OrganizationsOrgIdRouteImport.update({
  id: '/organizations/$orgId',
  path: '/organizations/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesNewRoute = MessagesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MessagesRoute,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => MessagesRoute,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsNewRoute = DocumentsNewRouteImport.update({
  id: '/documents/new',
  path: '/documents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocIdRoute = DocumentsDocIdRouteImport.update({
  id: '/documents/$docId',
  path: '/documents/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanchatRoute = DemoTanchatRouteImport.update({
  id: '/demo/tanchat',
  path: '/demo/tanchat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMcpTodosRoute = DemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterTemplatesIndexRoute = RosterTemplatesIndexRouteImport.update({
  id: '/roster/templates/',
  path: '/roster/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleGuitarsIndexRoute = ExampleGuitarsIndexRouteImport.update({
  id: '/example/guitars/',
  path: '/example/guitars/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffIndexRoute = AdminStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminStaffRoute,
} as any)
const RosterTemplatesNewRoute = RosterTemplatesNewRouteImport.update({
  id: '/roster/templates/new',
  path: '/roster/templates/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrgIdEditRoute = OrganizationsOrgIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => OrganizationsOrgIdRoute,
} as any)
const ExampleGuitarsGuitarIdRoute = ExampleGuitarsGuitarIdRouteImport.update({
  id: '/example/guitars/$guitarId',
  path: '/example/guitars/$guitarId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTanchatRoute = DemoApiTanchatRouteImport.update({
  id: '/demo/api/tanchat',
  path: '/demo/api/tanchat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiMcpTodosRoute = DemoApiMcpTodosRouteImport.update({
  id: '/demo/api/mcp-todos',
  path: '/demo/api/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStakeholdersVerificationRoute =
  AdminStakeholdersVerificationRouteImport.update({
    id: '/admin/stakeholders/verification',
    path: '/admin/stakeholders/verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminStaffNewRoute = AdminStaffNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminStaffRoute,
} as any)
const AdminRosterPlannerRoute = AdminRosterPlannerRouteImport.update({
  id: '/admin/roster/planner',
  path: '/admin/roster/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRegistryRoute = AdminAttendanceRegistryRouteImport.update({
  id: '/admin/attendance/registry',
  path: '/admin/attendance/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffIdEditRoute = AdminStaffIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminStaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/messages': typeof MessagesRouteWithChildren
  '/admin/staff': typeof AdminStaffRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanchat': typeof DemoTanchatRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/documents/$docId': typeof DocumentsDocIdRoute
  '/documents/new': typeof DocumentsNewRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/messages/new': typeof MessagesNewRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRouteWithChildren
  '/organizations/new': typeof OrganizationsNewRoute
  '/public/duty-board': typeof PublicDutyBoardRoute
  '/roster/generate': typeof RosterGenerateRoute
  '/roster/my-shifts': typeof RosterMyShiftsRoute
  '/stakeholder/activities': typeof StakeholderActivitiesRoute
  '/stakeholder/dashboard': typeof StakeholderDashboardRoute
  '/stakeholder/flights': typeof StakeholderFlightsRoute
  '/stakeholder/invoices': typeof StakeholderInvoicesRoute
  '/stakeholder/login': typeof StakeholderLoginRoute
  '/stakeholder/permits': typeof StakeholderPermitsRoute
  '/stakeholder/profile': typeof StakeholderProfileRoute
  '/stakeholder/register': typeof StakeholderRegisterRoute
  '/stakeholder/registration-success': typeof StakeholderRegistrationSuccessRoute
  '/stakeholders/$stakeholderId': typeof StakeholdersStakeholderIdRoute
  '/stakeholders/permits': typeof StakeholdersPermitsRoute
  '/stakeholders/verification': typeof StakeholdersVerificationRoute
  '/admin': typeof AdminIndexRoute
  '/attendance': typeof AttendanceIndexRoute
  '/certifications': typeof CertificationsIndexRoute
  '/contractors': typeof ContractorsIndexRoute
  '/departments': typeof DepartmentsIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/geofence': typeof GeofenceIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/inspections': typeof InspectionsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/positions': typeof PositionsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/rgm': typeof RgmIndexRoute
  '/roster': typeof RosterIndexRoute
  '/security': typeof SecurityIndexRoute
  '/self-service': typeof SelfServiceIndexRoute
  '/stakeholders': typeof StakeholdersIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/terminals': typeof TerminalsIndexRoute
  '/users': typeof UsersIndexRoute
  '/admin/attendance/registry': typeof AdminAttendanceRegistryRoute
  '/admin/roster/planner': typeof AdminRosterPlannerRoute
  '/admin/staff/new': typeof AdminStaffNewRoute
  '/admin/stakeholders/verification': typeof AdminStakeholdersVerificationRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tanchat': typeof DemoApiTanchatRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/organizations/$orgId/edit': typeof OrganizationsOrgIdEditRoute
  '/roster/templates/new': typeof RosterTemplatesNewRoute
  '/admin/staff/': typeof AdminStaffIndexRoute
  '/example/guitars': typeof ExampleGuitarsIndexRoute
  '/roster/templates': typeof RosterTemplatesIndexRoute
  '/admin/staff/$id/edit': typeof AdminStaffIdEditRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanchat': typeof DemoTanchatRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/documents/$docId': typeof DocumentsDocIdRoute
  '/documents/new': typeof DocumentsNewRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/messages/new': typeof MessagesNewRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRouteWithChildren
  '/organizations/new': typeof OrganizationsNewRoute
  '/public/duty-board': typeof PublicDutyBoardRoute
  '/roster/generate': typeof RosterGenerateRoute
  '/roster/my-shifts': typeof RosterMyShiftsRoute
  '/stakeholder/activities': typeof StakeholderActivitiesRoute
  '/stakeholder/dashboard': typeof StakeholderDashboardRoute
  '/stakeholder/flights': typeof StakeholderFlightsRoute
  '/stakeholder/invoices': typeof StakeholderInvoicesRoute
  '/stakeholder/login': typeof StakeholderLoginRoute
  '/stakeholder/permits': typeof StakeholderPermitsRoute
  '/stakeholder/profile': typeof StakeholderProfileRoute
  '/stakeholder/register': typeof StakeholderRegisterRoute
  '/stakeholder/registration-success': typeof StakeholderRegistrationSuccessRoute
  '/stakeholders/$stakeholderId': typeof StakeholdersStakeholderIdRoute
  '/stakeholders/permits': typeof StakeholdersPermitsRoute
  '/stakeholders/verification': typeof StakeholdersVerificationRoute
  '/admin': typeof AdminIndexRoute
  '/attendance': typeof AttendanceIndexRoute
  '/certifications': typeof CertificationsIndexRoute
  '/contractors': typeof ContractorsIndexRoute
  '/departments': typeof DepartmentsIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/geofence': typeof GeofenceIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/inspections': typeof InspectionsIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/positions': typeof PositionsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/rgm': typeof RgmIndexRoute
  '/roster': typeof RosterIndexRoute
  '/security': typeof SecurityIndexRoute
  '/self-service': typeof SelfServiceIndexRoute
  '/stakeholders': typeof StakeholdersIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/terminals': typeof TerminalsIndexRoute
  '/users': typeof UsersIndexRoute
  '/admin/attendance/registry': typeof AdminAttendanceRegistryRoute
  '/admin/roster/planner': typeof AdminRosterPlannerRoute
  '/admin/staff/new': typeof AdminStaffNewRoute
  '/admin/stakeholders/verification': typeof AdminStakeholdersVerificationRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tanchat': typeof DemoApiTanchatRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/organizations/$orgId/edit': typeof OrganizationsOrgIdEditRoute
  '/roster/templates/new': typeof RosterTemplatesNewRoute
  '/admin/staff': typeof AdminStaffIndexRoute
  '/example/guitars': typeof ExampleGuitarsIndexRoute
  '/roster/templates': typeof RosterTemplatesIndexRoute
  '/admin/staff/$id/edit': typeof AdminStaffIdEditRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/messages': typeof MessagesRouteWithChildren
  '/admin/staff': typeof AdminStaffRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanchat': typeof DemoTanchatRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/documents/$docId': typeof DocumentsDocIdRoute
  '/documents/new': typeof DocumentsNewRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/messages/new': typeof MessagesNewRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRouteWithChildren
  '/organizations/new': typeof OrganizationsNewRoute
  '/public/duty-board': typeof PublicDutyBoardRoute
  '/roster/generate': typeof RosterGenerateRoute
  '/roster/my-shifts': typeof RosterMyShiftsRoute
  '/stakeholder/activities': typeof StakeholderActivitiesRoute
  '/stakeholder/dashboard': typeof StakeholderDashboardRoute
  '/stakeholder/flights': typeof StakeholderFlightsRoute
  '/stakeholder/invoices': typeof StakeholderInvoicesRoute
  '/stakeholder/login': typeof StakeholderLoginRoute
  '/stakeholder/permits': typeof StakeholderPermitsRoute
  '/stakeholder/profile': typeof StakeholderProfileRoute
  '/stakeholder/register': typeof StakeholderRegisterRoute
  '/stakeholder/registration-success': typeof StakeholderRegistrationSuccessRoute
  '/stakeholders/$stakeholderId': typeof StakeholdersStakeholderIdRoute
  '/stakeholders/permits': typeof StakeholdersPermitsRoute
  '/stakeholders/verification': typeof StakeholdersVerificationRoute
  '/admin/': typeof AdminIndexRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/certifications/': typeof CertificationsIndexRoute
  '/contractors/': typeof ContractorsIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/geofence/': typeof GeofenceIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/inspections/': typeof InspectionsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/positions/': typeof PositionsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/rgm/': typeof RgmIndexRoute
  '/roster/': typeof RosterIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/self-service/': typeof SelfServiceIndexRoute
  '/stakeholders/': typeof StakeholdersIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/terminals/': typeof TerminalsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/admin/attendance/registry': typeof AdminAttendanceRegistryRoute
  '/admin/roster/planner': typeof AdminRosterPlannerRoute
  '/admin/staff/new': typeof AdminStaffNewRoute
  '/admin/stakeholders/verification': typeof AdminStakeholdersVerificationRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tanchat': typeof DemoApiTanchatRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/organizations/$orgId/edit': typeof OrganizationsOrgIdEditRoute
  '/roster/templates/new': typeof RosterTemplatesNewRoute
  '/admin/staff/': typeof AdminStaffIndexRoute
  '/example/guitars/': typeof ExampleGuitarsIndexRoute
  '/roster/templates/': typeof RosterTemplatesIndexRoute
  '/admin/staff/$id/edit': typeof AdminStaffIdEditRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/messages'
    | '/admin/staff'
    | '/auth/login'
    | '/auth/register'
    | '/demo/mcp-todos'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanchat'
    | '/demo/tanstack-query'
    | '/documents/$docId'
    | '/documents/new'
    | '/groups/$groupId'
    | '/messages/$conversationId'
    | '/messages/new'
    | '/organizations/$orgId'
    | '/organizations/new'
    | '/public/duty-board'
    | '/roster/generate'
    | '/roster/my-shifts'
    | '/stakeholder/activities'
    | '/stakeholder/dashboard'
    | '/stakeholder/flights'
    | '/stakeholder/invoices'
    | '/stakeholder/login'
    | '/stakeholder/permits'
    | '/stakeholder/profile'
    | '/stakeholder/register'
    | '/stakeholder/registration-success'
    | '/stakeholders/$stakeholderId'
    | '/stakeholders/permits'
    | '/stakeholders/verification'
    | '/admin'
    | '/attendance'
    | '/certifications'
    | '/contractors'
    | '/departments'
    | '/documents'
    | '/geofence'
    | '/groups'
    | '/inspections'
    | '/messages/'
    | '/organizations'
    | '/positions'
    | '/reports'
    | '/rgm'
    | '/roster'
    | '/security'
    | '/self-service'
    | '/stakeholders'
    | '/tasks'
    | '/terminals'
    | '/users'
    | '/admin/attendance/registry'
    | '/admin/roster/planner'
    | '/admin/staff/new'
    | '/admin/stakeholders/verification'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/api/tanchat'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/organizations/$orgId/edit'
    | '/roster/templates/new'
    | '/admin/staff/'
    | '/example/guitars'
    | '/roster/templates'
    | '/admin/staff/$id/edit'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/demo/mcp-todos'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanchat'
    | '/demo/tanstack-query'
    | '/documents/$docId'
    | '/documents/new'
    | '/groups/$groupId'
    | '/messages/$conversationId'
    | '/messages/new'
    | '/organizations/$orgId'
    | '/organizations/new'
    | '/public/duty-board'
    | '/roster/generate'
    | '/roster/my-shifts'
    | '/stakeholder/activities'
    | '/stakeholder/dashboard'
    | '/stakeholder/flights'
    | '/stakeholder/invoices'
    | '/stakeholder/login'
    | '/stakeholder/permits'
    | '/stakeholder/profile'
    | '/stakeholder/register'
    | '/stakeholder/registration-success'
    | '/stakeholders/$stakeholderId'
    | '/stakeholders/permits'
    | '/stakeholders/verification'
    | '/admin'
    | '/attendance'
    | '/certifications'
    | '/contractors'
    | '/departments'
    | '/documents'
    | '/geofence'
    | '/groups'
    | '/inspections'
    | '/messages'
    | '/organizations'
    | '/positions'
    | '/reports'
    | '/rgm'
    | '/roster'
    | '/security'
    | '/self-service'
    | '/stakeholders'
    | '/tasks'
    | '/terminals'
    | '/users'
    | '/admin/attendance/registry'
    | '/admin/roster/planner'
    | '/admin/staff/new'
    | '/admin/stakeholders/verification'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/api/tanchat'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/organizations/$orgId/edit'
    | '/roster/templates/new'
    | '/admin/staff'
    | '/example/guitars'
    | '/roster/templates'
    | '/admin/staff/$id/edit'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/messages'
    | '/admin/staff'
    | '/auth/login'
    | '/auth/register'
    | '/demo/mcp-todos'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanchat'
    | '/demo/tanstack-query'
    | '/documents/$docId'
    | '/documents/new'
    | '/groups/$groupId'
    | '/messages/$conversationId'
    | '/messages/new'
    | '/organizations/$orgId'
    | '/organizations/new'
    | '/public/duty-board'
    | '/roster/generate'
    | '/roster/my-shifts'
    | '/stakeholder/activities'
    | '/stakeholder/dashboard'
    | '/stakeholder/flights'
    | '/stakeholder/invoices'
    | '/stakeholder/login'
    | '/stakeholder/permits'
    | '/stakeholder/profile'
    | '/stakeholder/register'
    | '/stakeholder/registration-success'
    | '/stakeholders/$stakeholderId'
    | '/stakeholders/permits'
    | '/stakeholders/verification'
    | '/admin/'
    | '/attendance/'
    | '/certifications/'
    | '/contractors/'
    | '/departments/'
    | '/documents/'
    | '/geofence/'
    | '/groups/'
    | '/inspections/'
    | '/messages/'
    | '/organizations/'
    | '/positions/'
    | '/reports/'
    | '/rgm/'
    | '/roster/'
    | '/security/'
    | '/self-service/'
    | '/stakeholders/'
    | '/tasks/'
    | '/terminals/'
    | '/users/'
    | '/admin/attendance/registry'
    | '/admin/roster/planner'
    | '/admin/staff/new'
    | '/admin/stakeholders/verification'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/api/tanchat'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/organizations/$orgId/edit'
    | '/roster/templates/new'
    | '/admin/staff/'
    | '/example/guitars/'
    | '/roster/templates/'
    | '/admin/staff/$id/edit'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  AdminStaffRoute: typeof AdminStaffRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  DemoMcpTodosRoute: typeof DemoMcpTodosRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanchatRoute: typeof DemoTanchatRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DocumentsDocIdRoute: typeof DocumentsDocIdRoute
  DocumentsNewRoute: typeof DocumentsNewRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  OrganizationsOrgIdRoute: typeof OrganizationsOrgIdRouteWithChildren
  OrganizationsNewRoute: typeof OrganizationsNewRoute
  PublicDutyBoardRoute: typeof PublicDutyBoardRoute
  RosterGenerateRoute: typeof RosterGenerateRoute
  RosterMyShiftsRoute: typeof RosterMyShiftsRoute
  StakeholderActivitiesRoute: typeof StakeholderActivitiesRoute
  StakeholderDashboardRoute: typeof StakeholderDashboardRoute
  StakeholderFlightsRoute: typeof StakeholderFlightsRoute
  StakeholderInvoicesRoute: typeof StakeholderInvoicesRoute
  StakeholderLoginRoute: typeof StakeholderLoginRoute
  StakeholderPermitsRoute: typeof StakeholderPermitsRoute
  StakeholderProfileRoute: typeof StakeholderProfileRoute
  StakeholderRegisterRoute: typeof StakeholderRegisterRoute
  StakeholderRegistrationSuccessRoute: typeof StakeholderRegistrationSuccessRoute
  StakeholdersStakeholderIdRoute: typeof StakeholdersStakeholderIdRoute
  StakeholdersPermitsRoute: typeof StakeholdersPermitsRoute
  StakeholdersVerificationRoute: typeof StakeholdersVerificationRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AttendanceIndexRoute: typeof AttendanceIndexRoute
  CertificationsIndexRoute: typeof CertificationsIndexRoute
  ContractorsIndexRoute: typeof ContractorsIndexRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  GeofenceIndexRoute: typeof GeofenceIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  InspectionsIndexRoute: typeof InspectionsIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  PositionsIndexRoute: typeof PositionsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  RgmIndexRoute: typeof RgmIndexRoute
  RosterIndexRoute: typeof RosterIndexRoute
  SecurityIndexRoute: typeof SecurityIndexRoute
  SelfServiceIndexRoute: typeof SelfServiceIndexRoute
  StakeholdersIndexRoute: typeof StakeholdersIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TerminalsIndexRoute: typeof TerminalsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  AdminAttendanceRegistryRoute: typeof AdminAttendanceRegistryRoute
  AdminRosterPlannerRoute: typeof AdminRosterPlannerRoute
  AdminStakeholdersVerificationRoute: typeof AdminStakeholdersVerificationRoute
  DemoApiMcpTodosRoute: typeof DemoApiMcpTodosRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTanchatRoute: typeof DemoApiTanchatRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ExampleGuitarsGuitarIdRoute: typeof ExampleGuitarsGuitarIdRoute
  RosterTemplatesNewRoute: typeof RosterTemplatesNewRoute
  ExampleGuitarsIndexRoute: typeof ExampleGuitarsIndexRoute
  RosterTemplatesIndexRoute: typeof RosterTemplatesIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminals/': {
      id: '/terminals/'
      path: '/terminals'
      fullPath: '/terminals'
      preLoaderRoute: typeof TerminalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholders/': {
      id: '/stakeholders/'
      path: '/stakeholders'
      fullPath: '/stakeholders'
      preLoaderRoute: typeof StakeholdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-service/': {
      id: '/self-service/'
      path: '/self-service'
      fullPath: '/self-service'
      preLoaderRoute: typeof SelfServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/': {
      id: '/security/'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/': {
      id: '/roster/'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rgm/': {
      id: '/rgm/'
      path: '/rgm'
      fullPath: '/rgm'
      preLoaderRoute: typeof RgmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions/': {
      id: '/positions/'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/inspections/': {
      id: '/inspections/'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof InspectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofence/': {
      id: '/geofence/'
      path: '/geofence'
      fullPath: '/geofence'
      preLoaderRoute: typeof GeofenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/': {
      id: '/departments/'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractors/': {
      id: '/contractors/'
      path: '/contractors'
      fullPath: '/contractors'
      preLoaderRoute: typeof ContractorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications/': {
      id: '/certifications/'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/': {
      id: '/attendance/'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholders/verification': {
      id: '/stakeholders/verification'
      path: '/stakeholders/verification'
      fullPath: '/stakeholders/verification'
      preLoaderRoute: typeof StakeholdersVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholders/permits': {
      id: '/stakeholders/permits'
      path: '/stakeholders/permits'
      fullPath: '/stakeholders/permits'
      preLoaderRoute: typeof StakeholdersPermitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholders/$stakeholderId': {
      id: '/stakeholders/$stakeholderId'
      path: '/stakeholders/$stakeholderId'
      fullPath: '/stakeholders/$stakeholderId'
      preLoaderRoute: typeof StakeholdersStakeholderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholder/registration-success': {
      id: '/stakeholder/registration-success'
      path: '/stakeholder/registration-success'
      fullPath: '/stakeholder/registration-success'
      preLoaderRoute: typeof StakeholderRegistrationSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholder/register': {
      id: '/stakeholder/register'
      path: '/stakeholder/register'
      fullPath: '/stakeholder/register'
      preLoaderRoute: typeof StakeholderRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholder/profile': {
      id: '/stakeholder/profile'
      path: '/stakeholder/profile'
      fullPath: '/stakeholder/profile'
      preLoaderRoute: typeof StakeholderProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholder/permits': {
      id: '/stakeholder/permits'
      path: '/stakeholder/permits'
      fullPath: '/stakeholder/permits'
      preLoaderRoute: typeof StakeholderPermitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholder/login': {
      id: '/stakeholder/login'
      path: '/stakeholder/login'
      fullPath: '/stakeholder/login'
      preLoaderRoute: typeof StakeholderLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholder/invoices': {
      id: '/stakeholder/invoices'
      path: '/stakeholder/invoices'
      fullPath: '/stakeholder/invoices'
      preLoaderRoute: typeof StakeholderInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholder/flights': {
      id: '/stakeholder/flights'
      path: '/stakeholder/flights'
      fullPath: '/stakeholder/flights'
      preLoaderRoute: typeof StakeholderFlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholder/dashboard': {
      id: '/stakeholder/dashboard'
      path: '/stakeholder/dashboard'
      fullPath: '/stakeholder/dashboard'
      preLoaderRoute: typeof StakeholderDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholder/activities': {
      id: '/stakeholder/activities'
      path: '/stakeholder/activities'
      fullPath: '/stakeholder/activities'
      preLoaderRoute: typeof StakeholderActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/my-shifts': {
      id: '/roster/my-shifts'
      path: '/roster/my-shifts'
      fullPath: '/roster/my-shifts'
      preLoaderRoute: typeof RosterMyShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/generate': {
      id: '/roster/generate'
      path: '/roster/generate'
      fullPath: '/roster/generate'
      preLoaderRoute: typeof RosterGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/duty-board': {
      id: '/public/duty-board'
      path: '/public/duty-board'
      fullPath: '/public/duty-board'
      preLoaderRoute: typeof PublicDutyBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/new': {
      id: '/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof OrganizationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$orgId': {
      id: '/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof OrganizationsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/new': {
      id: '/messages/new'
      path: '/new'
      fullPath: '/messages/new'
      preLoaderRoute: typeof MessagesNewRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/new': {
      id: '/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof DocumentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$docId': {
      id: '/documents/$docId'
      path: '/documents/$docId'
      fullPath: '/documents/$docId'
      preLoaderRoute: typeof DocumentsDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanchat': {
      id: '/demo/tanchat'
      path: '/demo/tanchat'
      fullPath: '/demo/tanchat'
      preLoaderRoute: typeof DemoTanchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mcp-todos': {
      id: '/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof DemoMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/templates/': {
      id: '/roster/templates/'
      path: '/roster/templates'
      fullPath: '/roster/templates'
      preLoaderRoute: typeof RosterTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/guitars/': {
      id: '/example/guitars/'
      path: '/example/guitars'
      fullPath: '/example/guitars'
      preLoaderRoute: typeof ExampleGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff/': {
      id: '/admin/staff/'
      path: '/'
      fullPath: '/admin/staff/'
      preLoaderRoute: typeof AdminStaffIndexRouteImport
      parentRoute: typeof AdminStaffRoute
    }
    '/roster/templates/new': {
      id: '/roster/templates/new'
      path: '/roster/templates/new'
      fullPath: '/roster/templates/new'
      preLoaderRoute: typeof RosterTemplatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$orgId/edit': {
      id: '/organizations/$orgId/edit'
      path: '/edit'
      fullPath: '/organizations/$orgId/edit'
      preLoaderRoute: typeof OrganizationsOrgIdEditRouteImport
      parentRoute: typeof OrganizationsOrgIdRoute
    }
    '/example/guitars/$guitarId': {
      id: '/example/guitars/$guitarId'
      path: '/example/guitars/$guitarId'
      fullPath: '/example/guitars/$guitarId'
      preLoaderRoute: typeof ExampleGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tanchat': {
      id: '/demo/api/tanchat'
      path: '/demo/api/tanchat'
      fullPath: '/demo/api/tanchat'
      preLoaderRoute: typeof DemoApiTanchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/mcp-todos': {
      id: '/demo/api/mcp-todos'
      path: '/demo/api/mcp-todos'
      fullPath: '/demo/api/mcp-todos'
      preLoaderRoute: typeof DemoApiMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stakeholders/verification': {
      id: '/admin/stakeholders/verification'
      path: '/admin/stakeholders/verification'
      fullPath: '/admin/stakeholders/verification'
      preLoaderRoute: typeof AdminStakeholdersVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff/new': {
      id: '/admin/staff/new'
      path: '/new'
      fullPath: '/admin/staff/new'
      preLoaderRoute: typeof AdminStaffNewRouteImport
      parentRoute: typeof AdminStaffRoute
    }
    '/admin/roster/planner': {
      id: '/admin/roster/planner'
      path: '/admin/roster/planner'
      fullPath: '/admin/roster/planner'
      preLoaderRoute: typeof AdminRosterPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance/registry': {
      id: '/admin/attendance/registry'
      path: '/admin/attendance/registry'
      fullPath: '/admin/attendance/registry'
      preLoaderRoute: typeof AdminAttendanceRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff/$id/edit': {
      id: '/admin/staff/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/staff/$id/edit'
      preLoaderRoute: typeof AdminStaffIdEditRouteImport
      parentRoute: typeof AdminStaffRoute
    }
  }
}

interface MessagesRouteChildren {
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
  MessagesNewRoute: typeof MessagesNewRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesConversationIdRoute: MessagesConversationIdRoute,
  MessagesNewRoute: MessagesNewRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface AdminStaffRouteChildren {
  AdminStaffNewRoute: typeof AdminStaffNewRoute
  AdminStaffIndexRoute: typeof AdminStaffIndexRoute
  AdminStaffIdEditRoute: typeof AdminStaffIdEditRoute
}

const AdminStaffRouteChildren: AdminStaffRouteChildren = {
  AdminStaffNewRoute: AdminStaffNewRoute,
  AdminStaffIndexRoute: AdminStaffIndexRoute,
  AdminStaffIdEditRoute: AdminStaffIdEditRoute,
}

const AdminStaffRouteWithChildren = AdminStaffRoute._addFileChildren(
  AdminStaffRouteChildren,
)

interface OrganizationsOrgIdRouteChildren {
  OrganizationsOrgIdEditRoute: typeof OrganizationsOrgIdEditRoute
}

const OrganizationsOrgIdRouteChildren: OrganizationsOrgIdRouteChildren = {
  OrganizationsOrgIdEditRoute: OrganizationsOrgIdEditRoute,
}

const OrganizationsOrgIdRouteWithChildren =
  OrganizationsOrgIdRoute._addFileChildren(OrganizationsOrgIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MessagesRoute: MessagesRouteWithChildren,
  AdminStaffRoute: AdminStaffRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  DemoMcpTodosRoute: DemoMcpTodosRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanchatRoute: DemoTanchatRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DocumentsDocIdRoute: DocumentsDocIdRoute,
  DocumentsNewRoute: DocumentsNewRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  OrganizationsOrgIdRoute: OrganizationsOrgIdRouteWithChildren,
  OrganizationsNewRoute: OrganizationsNewRoute,
  PublicDutyBoardRoute: PublicDutyBoardRoute,
  RosterGenerateRoute: RosterGenerateRoute,
  RosterMyShiftsRoute: RosterMyShiftsRoute,
  StakeholderActivitiesRoute: StakeholderActivitiesRoute,
  StakeholderDashboardRoute: StakeholderDashboardRoute,
  StakeholderFlightsRoute: StakeholderFlightsRoute,
  StakeholderInvoicesRoute: StakeholderInvoicesRoute,
  StakeholderLoginRoute: StakeholderLoginRoute,
  StakeholderPermitsRoute: StakeholderPermitsRoute,
  StakeholderProfileRoute: StakeholderProfileRoute,
  StakeholderRegisterRoute: StakeholderRegisterRoute,
  StakeholderRegistrationSuccessRoute: StakeholderRegistrationSuccessRoute,
  StakeholdersStakeholderIdRoute: StakeholdersStakeholderIdRoute,
  StakeholdersPermitsRoute: StakeholdersPermitsRoute,
  StakeholdersVerificationRoute: StakeholdersVerificationRoute,
  AdminIndexRoute: AdminIndexRoute,
  AttendanceIndexRoute: AttendanceIndexRoute,
  CertificationsIndexRoute: CertificationsIndexRoute,
  ContractorsIndexRoute: ContractorsIndexRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
  GeofenceIndexRoute: GeofenceIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  InspectionsIndexRoute: InspectionsIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  PositionsIndexRoute: PositionsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  RgmIndexRoute: RgmIndexRoute,
  RosterIndexRoute: RosterIndexRoute,
  SecurityIndexRoute: SecurityIndexRoute,
  SelfServiceIndexRoute: SelfServiceIndexRoute,
  StakeholdersIndexRoute: StakeholdersIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  TerminalsIndexRoute: TerminalsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  AdminAttendanceRegistryRoute: AdminAttendanceRegistryRoute,
  AdminRosterPlannerRoute: AdminRosterPlannerRoute,
  AdminStakeholdersVerificationRoute: AdminStakeholdersVerificationRoute,
  DemoApiMcpTodosRoute: DemoApiMcpTodosRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTanchatRoute: DemoApiTanchatRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ExampleGuitarsGuitarIdRoute: ExampleGuitarsGuitarIdRoute,
  RosterTemplatesNewRoute: RosterTemplatesNewRoute,
  ExampleGuitarsIndexRoute: ExampleGuitarsIndexRoute,
  RosterTemplatesIndexRoute: RosterTemplatesIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
